import { generateIOTests } from "../support/e2e";

const inputs = {
  motor: "motor",
  efficiency: "efficiency",
  shooterRPM: "shooterRPM",
  currentLimit: "currentLimit",
  shooterRatio: "shooterRatio",
  projectileWeight: "projectileWeight",
  shooterRadius: "shooterRadius",
  shooterWeight: "shooterWeight",
  flywheelRadius: "flywheelRadius",
  flywheelWeight: "flywheelWeight",
  flywheelShooterRatio: "flywheelShooterRatio",
};

const inputSelects = {
  motor: "selectmotor",
  shooterRPM: "selectshooterRPM",
  currentLimit: "selectcurrentLimit",
  shooterRatio: "selectshooterRatio",
  projectileWeight: "selectprojectileWeight",
  shooterRadius: "selectshooterRadius",
  shooterWeight: "selectshooterWeight",
  flywheelRadius: "selectflywheelRadius",
  flywheelWeight: "selectflywheelWeight",
  flywheelShooterRatio: "selectflywheelShooterRatio",
};

const secondaryInputs = {};

const outputs = {
  shooterMaxSpeed: "shooterMaxSpeed",
  customShooterMOI: "customShooterMOI",
  customFlywheelMOI: "customFlywheelMOI",
  windupTime: "windupTime",
  recoveryTime: "recoveryTime",
  surfaceSpeed: "surfaceSpeed",
  projectileSpeed: "projectileSpeed",
  speedAfterShot: "speedAfterShot",
  flywheelEnergy: "flywheelEnergy",
  projectileEnergy: "projectileEnergy",
  estimatedKV: "estimatedKV",
  estimatedKA: "estimatedKA",
  responseTime: "responseTime",
};

const outputSelects = {
  shooterMaxSpeed: "selectshooterMaxSpeed",
  customShooterMOI: "selectcustomShooterMOI",
  customFlywheelMOI: "selectcustomFlywheelMOI",
  windupTime: "selectwindupTime",
  recoveryTime: "selectrecoveryTime",
  surfaceSpeed: "selectsurfaceSpeed",
  projectileSpeed: "selectprojectileSpeed",
  speedAfterShot: "selectspeedAfterShot",
  flywheelEnergy: "selectflywheelEnergy",
  projectileEnergy: "selectprojectileEnergy",
  estimatedKV: "selectestimatedKV",
  estimatedKA: "selectestimatedKA",
  responseTime: "selectresponseTime",
};

const allSelects = { ...inputSelects, ...outputSelects };

describe("Flywheel Calculator e2e tests", () => {
  beforeEach(() => {
    cy.visit("localhost:3000/flywheel", {
      onBeforeLoad(win) {
        cy.spy(win.navigator.clipboard, "writeText").as("copy");
      },
    });
  });

  it("has a visible title", () => {
    cy.get("p")
      .first()
      .should("be.visible")
      .should("have.text", "Flywheel Calculator");
  });

  it("copy link button works", () => {
    cy.contains("Copy Link", { timeout: 1000 * 60 })
      .should("be.visible")
      .click();
    cy.get("@copy").should(
      "have.been.calledWithExactly",
      "http://localhost:3000/flywheel?currentLimit=%7B%22s%22%3A40%2C%22u%22%3A%22A%22%7D&efficiency=100&flywheelMomentOfInertia=%7B%22s%22%3A3%2C%22u%22%3A%22in2%2Albs%22%7D&flywheelRadius=%7B%22s%22%3A2%2C%22u%22%3A%22in%22%7D&flywheelRatio=%7B%22magnitude%22%3A1%2C%22ratioType%22%3A%22Reduction%22%7D&flywheelWeight=%7B%22s%22%3A1.5%2C%22u%22%3A%22lbs%22%7D&motor=%7B%22quantity%22%3A2%2C%22name%22%3A%22NEO%22%7D&motorRatio=%7B%22magnitude%22%3A2%2C%22ratioType%22%3A%22Step-up%22%7D&projectileRadius=%7B%22s%22%3A2%2C%22u%22%3A%22in%22%7D&projectileWeight=%7B%22s%22%3A5%2C%22u%22%3A%22lbs%22%7D&shooterMomentOfInertia=%7B%22s%22%3A4.5%2C%22u%22%3A%22in2%2Albs%22%7D&shooterRadius=%7B%22s%22%3A3%2C%22u%22%3A%22in%22%7D&shooterTargetSpeed=%7B%22s%22%3A11000%2C%22u%22%3A%22rpm%22%7D&shooterWeight=%7B%22s%22%3A1%2C%22u%22%3A%22lbs%22%7D&useCustomFlywheelMoi=0&useCustomShooterMoi=0",
    );
  });

  generateIOTests<
    typeof inputs,
    typeof outputs,
    typeof allSelects,
    typeof secondaryInputs
  >(
    { name: "Flywheel Calculator", url: "localhost:3000/flywheel" },
    inputs,
    outputs,
    allSelects,
    [
      [
        { change: { key: "motor", value: "4" } },
        {
          efficiency: 100,
          shooterRPM: 11000,
          currentLimit: 40,
          shooterRatio: 2,
          projectileWeight: 5,
          shooterRadius: 3,
          shooterWeight: 1,
          flywheelRadius: 2,
          flywheelWeight: 1.5,
          flywheelShooterRatio: 1,
          shooterMaxSpeed: 11760,
          customShooterMOI: "4.500",
          customFlywheelMOI: "3.000",
          windupTime: 2.64,
          recoveryTime: 0.6129,
          surfaceSpeed: 287.98,
          projectileSpeed: 27.69,
          speedAfterShot: 10564,
          flywheelEnergy: 1456,
          projectileEnergy: 113,
          estimatedKV: 0.13,
          estimatedKA: 1.11,
          responseTime: 8.67,
        },
      ],
      [
        { change: { key: "efficiency", value: "95" } },
        {
          motor: 2,
          shooterRPM: 11000,
          currentLimit: 40,
          shooterRatio: 2,
          projectileWeight: 5,
          shooterRadius: 3,
          shooterWeight: 1,
          flywheelRadius: 2,
          flywheelWeight: 1.5,
          flywheelShooterRatio: 1,
          shooterMaxSpeed: 11760,
          customShooterMOI: "4.500",
          customFlywheelMOI: "3.000",
          windupTime: 5.56,
          recoveryTime: 1.2903,
          surfaceSpeed: 287.98,
          projectileSpeed: 27.69,
          speedAfterShot: 10564,
          flywheelEnergy: 1456,
          projectileEnergy: 113,
          estimatedKV: 0.13,
          estimatedKA: 2.33,
          responseTime: 18.26,
        },
      ],
      [
        { change: { key: "shooterRPM", value: "5679" } },
        {
          motor: 2,
          efficiency: 100,
          currentLimit: 40,
          shooterRatio: 2,
          projectileWeight: 5,
          shooterRadius: 3,
          shooterWeight: 1,
          flywheelRadius: 2,
          flywheelWeight: 1.5,
          flywheelShooterRatio: 1,
          shooterMaxSpeed: 11760,
          customShooterMOI: "4.500",
          customFlywheelMOI: "3.000",
          windupTime: 1.27,
          recoveryTime: 0.1042,
          surfaceSpeed: 148.68,
          projectileSpeed: "14.30",
          speedAfterShot: 5454,
          flywheelEnergy: 388,
          projectileEnergy: 30,
          estimatedKV: 0.13,
          estimatedKA: 2.22,
          responseTime: 17.34,
        },
      ],
      [
        { change: { key: "currentLimit", value: "55" } },
        {
          motor: 2,
          efficiency: 100,
          shooterRPM: 11000,
          shooterRatio: 2,
          projectileWeight: 5,
          shooterRadius: 3,
          shooterWeight: 1,
          flywheelRadius: 2,
          flywheelWeight: 1.5,
          flywheelShooterRatio: 1,
          shooterMaxSpeed: 11760,
          customShooterMOI: "4.500",
          customFlywheelMOI: "3.000",
          windupTime: "3.80",
          recoveryTime: 0.8834,
          surfaceSpeed: 287.98,
          projectileSpeed: 27.69,
          speedAfterShot: 10564,
          flywheelEnergy: 1456,
          projectileEnergy: 113,
          estimatedKV: 0.13,
          estimatedKA: "1.60",
          responseTime: "12.50",
        },
      ],
      [
        { change: { key: "shooterRatio", value: "3" } },
        {
          motor: 2,
          efficiency: 100,
          shooterRPM: 11000,
          currentLimit: 40,
          projectileWeight: 5,
          shooterRadius: 3,
          shooterWeight: 1,
          flywheelRadius: 2,
          flywheelWeight: 1.5,
          flywheelShooterRatio: 1,
          shooterMaxSpeed: 17640,
          customShooterMOI: "4.500",
          customFlywheelMOI: "3.000",
          windupTime: 2.82,
          recoveryTime: 0.4087,
          surfaceSpeed: 287.98,
          projectileSpeed: 27.69,
          speedAfterShot: 10564,
          flywheelEnergy: 1456,
          projectileEnergy: 113,
          estimatedKV: 0.09,
          estimatedKA: 4.99,
          responseTime: 58.53,
        },
      ],
      [
        { change: { key: "projectileWeight", value: "4" } },
        {
          motor: 2,
          efficiency: 100,
          shooterRPM: 11000,
          currentLimit: 40,
          shooterRatio: 2,
          shooterRadius: 3,
          shooterWeight: 1,
          flywheelRadius: 2,
          flywheelWeight: 1.5,
          flywheelShooterRatio: 1,
          shooterMaxSpeed: 11760,
          customShooterMOI: "4.500",
          customFlywheelMOI: "3.000",
          windupTime: 5.28,
          recoveryTime: 1.4192,
          surfaceSpeed: 287.98,
          projectileSpeed: 33.03,
          speedAfterShot: 10503,
          flywheelEnergy: 1456,
          projectileEnergy: 129,
          estimatedKV: 0.13,
          estimatedKA: 2.22,
          responseTime: 17.34,
        },
      ],
      [
        { change: { key: "shooterRadius", value: "4" } },
        {
          motor: 2,
          efficiency: 100,
          shooterRPM: 11000,
          currentLimit: 40,
          shooterRatio: 2,
          projectileWeight: 5,
          shooterWeight: 1,
          flywheelRadius: 2,
          flywheelWeight: 1.5,
          flywheelShooterRatio: 1,
          shooterMaxSpeed: 11760,
          customShooterMOI: "8.000",
          customFlywheelMOI: "3.000",
          windupTime: 7.74,
          recoveryTime: "1.5480",
          surfaceSpeed: 383.97,
          projectileSpeed: 31.52,
          speedAfterShot: 10616,
          flywheelEnergy: 2136,
          projectileEnergy: 147,
          estimatedKV: "0.10",
          estimatedKA: 4.34,
          responseTime: 45.22,
        },
      ],
      [
        { change: { key: "shooterWeight", value: "5" } },
        {
          motor: 2,
          efficiency: 100,
          shooterRPM: 11000,
          currentLimit: 40,
          shooterRatio: 2,
          projectileWeight: 5,
          shooterRadius: 3,
          flywheelRadius: 2,
          flywheelWeight: 1.5,
          flywheelShooterRatio: 1,
          shooterMaxSpeed: 11760,
          customShooterMOI: "22.500",
          customFlywheelMOI: "3.000",
          windupTime: 17.95,
          recoveryTime: 6.8046,
          surfaceSpeed: 287.98,
          projectileSpeed: 64.42,
          speedAfterShot: 10298,
          flywheelEnergy: 4951,
          projectileEnergy: 612,
          estimatedKV: 0.13,
          estimatedKA: 7.54,
          responseTime: 58.97,
        },
      ],
      [
        { change: { key: "flywheelRadius", value: "4" } },
        {
          motor: 2,
          efficiency: 100,
          shooterRPM: 11000,
          currentLimit: 40,
          shooterRatio: 2,
          projectileWeight: 5,
          shooterRadius: 3,
          shooterWeight: 1,
          flywheelWeight: 1.5,
          flywheelShooterRatio: 1,
          shooterMaxSpeed: 11760,
          customShooterMOI: "4.500",
          customFlywheelMOI: "12.000",
          windupTime: 11.61,
          recoveryTime: 4.0272,
          surfaceSpeed: 287.98,
          projectileSpeed: "49.50",
          speedAfterShot: 10361,
          flywheelEnergy: 3204,
          projectileEnergy: 361,
          estimatedKV: 0.13,
          estimatedKA: 1.22,
          responseTime: 9.54,
        },
      ],
      [
        { change: { key: "flywheelWeight", value: "2" } },
        {
          motor: 2,
          efficiency: 100,
          shooterRPM: 11000,
          currentLimit: 40,
          shooterRatio: 2,
          projectileWeight: 5,
          shooterRadius: 3,
          shooterWeight: 1,
          flywheelRadius: 2,
          flywheelShooterRatio: 1,
          shooterMaxSpeed: 11760,
          customShooterMOI: "4.500",
          customFlywheelMOI: "4.000",
          windupTime: 5.98,
          recoveryTime: 1.5134,
          surfaceSpeed: 287.98,
          projectileSpeed: "30.60",
          speedAfterShot: 10530,
          flywheelEnergy: 1650,
          projectileEnergy: 138,
          estimatedKV: 0.13,
          estimatedKA: 2.51,
          responseTime: 19.66,
        },
      ],
      [
        { change: { key: "flywheelShooterRatio", value: "5" } },
        {
          motor: 2,
          efficiency: 100,
          shooterRPM: 11000,
          currentLimit: 40,
          shooterRatio: 2,
          projectileWeight: 5,
          shooterRadius: 3,
          shooterWeight: 1,
          flywheelRadius: 2,
          flywheelWeight: 1.5,
          shooterMaxSpeed: 11760,
          customShooterMOI: "4.500",
          customFlywheelMOI: "3.000",
          windupTime: 3.25,
          recoveryTime: 0.4938,
          surfaceSpeed: 287.98,
          projectileSpeed: 18.42,
          speedAfterShot: 10689,
          flywheelEnergy: 897,
          projectileEnergy: 50,
          estimatedKV: 0.13,
          estimatedKA: 1.37,
          responseTime: 10.68,
        },
      ],
    ],
    secondaryInputs,
  );
});

export default {};
